# Generated by Django 5.2.8 on 2025-11-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('codigo_validacion', models.CharField(max_length=20)),
                ('registrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_nombre', models.CharField(max_length=100)),
                ('tutor_apellido', models.CharField(max_length=100)),
                ('tutor_email', models.EmailField(max_length=254)),
                ('tutor_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('ninio_nombre', models.CharField(max_length=100)),
                ('ninio_apellido', models.CharField(max_length=100)),
                ('ninio_edad', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('vacantes', 'Vacantes / Inscripciones'), ('general', 'Consulta General'), ('salud', 'Salud / Alergias'), ('horario', 'Horario / Jornada'), ('comercial', 'Comercial / Precios')], default='general', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
